import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';

const PrivacyPolicyPage = () => {
  useEffect(() => {
    document.title = "Privacy Policy | Bot and Table";
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="bg-white text-gray-900 min-h-screen">
      {/* Header */}
      <div className="bg-gray-50 py-16 mt-20">
        <div className="container mx-auto max-w-4xl px-4">
          <Link 
            to="/" 
            className="inline-flex items-center text-orange-600 hover:text-orange-700 mb-6 transition-colors"
          >
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Home
          </Link>
          <h1 className="text-4xl font-bold text-gray-900 mb-4">Privacy Policy</h1>
          <p className="text-xl text-gray-600">Last updated: {new Date().toLocaleDateString()}</p>
        </div>
      </div>

      {/* Content */}
      <div className="container mx-auto max-w-4xl px-4 py-12">
        <div className="prose prose-lg max-w-none">
          
          <p className="text-gray-700 mb-6 leading-relaxed">
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
          </p>
          
          <p className="text-gray-700 mb-8 leading-relaxed">
            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
          </p>

          <h2 className="text-2xl font-bold text-gray-900 mb-4">Interpretation & Definitions</h2>
          
          <h3 className="text-xl font-semibold text-gray-900 mb-3">Interpretation</h3>
          <p className="text-gray-700 mb-6 leading-relaxed">
            The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </p>

          <h3 className="text-xl font-semibold text-gray-900 mb-3">Definitions</h3>
          <p className="text-gray-700 mb-4 leading-relaxed">For the purposes of this Privacy Policy:</p>
          
          <div className="space-y-4 mb-8">
            <p className="text-gray-700 leading-relaxed"><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p>
            <p className="text-gray-700 leading-relaxed"><strong>Partner</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more equity interest or other securities entitled to vote for election of directors or other managing authority.</p>
            <p className="text-gray-700 leading-relaxed"><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to , 2842 North Whistle Post Drive, Fayetteville Arkansas 72704.</p>
            <p className="text-gray-700 leading-relaxed"><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
            <p className="text-gray-700 leading-relaxed"><strong>Country</strong> refers to: Arkansas, US</p>
            <p className="text-gray-700 leading-relaxed"><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
            <p className="text-gray-700 leading-relaxed"><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p>
            <p className="text-gray-700 leading-relaxed"><strong>Service</strong> refers to the Website.</p>
            <p className="text-gray-700 leading-relaxed"><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
            <p className="text-gray-700 leading-relaxed"><strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.</p>
            <p className="text-gray-700 leading-relaxed"><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
            <p className="text-gray-700 leading-relaxed"><strong>Website</strong> refers to BotandTable accessible from</p>
            <p className="text-gray-700 leading-relaxed"><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
          </div>

          <h2 className="text-2xl font-bold text-gray-900 mb-4">Collecting and Using Your Personal Data</h2>
          
          <h3 className="text-xl font-semibold text-gray-900 mb-3">Types of Data Collected</h3>
          
          <h4 className="text-lg font-semibold text-gray-900 mb-3">Personal Data</h4>
          <p className="text-gray-700 mb-4 leading-relaxed">
            While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
          </p>
          
          <ul className="list-disc pl-6 mb-6 space-y-1 text-gray-700">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
            <li>Usage Data</li>
          </ul>

          <h4 className="text-lg font-semibold text-gray-900 mb-3">Usage Data</h4>
          <p className="text-gray-700 mb-4 leading-relaxed">
            Usage Data is collected automatically when using the Service.
          </p>
          <p className="text-gray-700 mb-8 leading-relaxed">
            No mobile information will be shared with third parties/affiliates for marketing/promotional purposes. Information sharing to subcontractors in support services, such as customer service is permitted. All other use case categories exclude text messaging originator opt-in data and consent; this information will not be shared with any third parties.
          </p>

          <h3 className="text-xl font-semibold text-gray-900 mb-3">Tracking Technologies and Cookies</h3>
          <p className="text-gray-700 mb-4 leading-relaxed">
            We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
          </p>

          <div className="space-y-4 mb-6">
            <p className="text-gray-700 leading-relaxed">
              <strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.
            </p>
            
            <p className="text-gray-700 leading-relaxed">
              <strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).
            </p>
          </div>

          <p className="text-gray-700 mb-4 leading-relaxed">
            Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. Learn more about cookies on the Free Privacy Policy website article.
          </p>

          <p className="text-gray-700 mb-4 leading-relaxed">
            We use both Session and Persistent Cookies for the purposes set out below:
          </p>

          <div className="space-y-6 mb-8">
            <div className="bg-gray-50 p-4 rounded-lg">
              <h5 className="font-semibold text-gray-900 mb-2">Necessary / Essential Cookies</h5>
              <p className="text-sm text-gray-700 mb-1"><strong>Type:</strong> Session Cookies</p>
              <p className="text-sm text-gray-700 mb-1"><strong>Administered by:</strong> Us</p>
              <p className="text-sm text-gray-700"><strong>Purpose:</strong> These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
            </div>

            <div className="bg-gray-50 p-4 rounded-lg">
              <h5 className="font-semibold text-gray-900 mb-2">Cookies Policy / Notice Acceptance Cookies</h5>
              <p className="text-sm text-gray-700 mb-1"><strong>Type:</strong> Persistent Cookies</p>
              <p className="text-sm text-gray-700 mb-1"><strong>Administered by:</strong> Us</p>
              <p className="text-sm text-gray-700"><strong>Purpose:</strong> These Cookies identify if users have accepted the use of cookies on the Website.</p>
            </div>

            <div className="bg-gray-50 p-4 rounded-lg">
              <h5 className="font-semibold text-gray-900 mb-2">Functionality Cookies</h5>
              <p className="text-sm text-gray-700 mb-1"><strong>Type:</strong> Persistent Cookies</p>
              <p className="text-sm text-gray-700 mb-1"><strong>Administered by:</strong> Us</p>
              <p className="text-sm text-gray-700"><strong>Purpose:</strong> These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
            </div>

            <div className="bg-gray-50 p-4 rounded-lg">
              <h5 className="font-semibold text-gray-900 mb-2">Tracking and Performance Cookies</h5>
              <p className="text-sm text-gray-700 mb-1"><strong>Type:</strong> Persistent Cookies</p>
              <p className="text-sm text-gray-700 mb-1"><strong>Administered by:</strong> Third-Parties</p>
              <p className="text-sm text-gray-700"><strong>Purpose:</strong> These Cookies are used to track information about traffic to the Website and how users use the Website. The information gathered via these Cookies may directly or indirectly identify you as an individual visitor. This is because the information collected is typically linked to a pseudonymous identifier associated with the device you use to access the Website. We may also use these Cookies to test new pages, features or new functionality of the Website to see how our users react to them.</p>
            </div>
          </div>

          <p className="text-gray-700 mb-8 leading-relaxed">
            For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.
          </p>

          <h3 className="text-xl font-semibold text-gray-900 mb-3">Use of Your Personal Data</h3>
          <p className="text-gray-700 mb-4 leading-relaxed">The Company may use Personal Data for the following purposes:</p>
          
          <ul className="list-disc pl-6 mb-8 space-y-2 text-gray-700">
            <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
            <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
            <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
            <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
            <li><strong>To provide You</strong> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
            <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
            <li><strong>To deliver targeted advertising to You:</strong> We may use Your information to develop and display content and advertising (and work with third-party vendors who do so) tailored to Your interests and/or location and to measure its effectiveness.</li>
            <li><strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</li>
            <li><strong>For other purposes:</strong> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
          </ul>

          <h3 className="text-xl font-semibold text-gray-900 mb-3">Retention of Your Personal Data</h3>
          <p className="text-gray-700 mb-4 leading-relaxed">
            The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
          </p>
          <p className="text-gray-700 mb-8 leading-relaxed">
            The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.
          </p>

          <h3 className="text-xl font-semibold text-gray-900 mb-3">Transfer of Your Personal Data</h3>
          <p className="text-gray-700 mb-4 leading-relaxed">
            Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
          </p>
          <p className="text-gray-700 mb-4 leading-relaxed">
            Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
          </p>
          <p className="text-gray-700 mb-8 leading-relaxed">
            The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.
          </p>

          <h3 className="text-xl font-semibold text-gray-900 mb-3">Delete Your Personal Data</h3>
          <p className="text-gray-700 mb-4 leading-relaxed">
            You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
          </p>
          <p className="text-gray-700 mb-4 leading-relaxed">
            Our Service may give You the ability to delete certain information about You from within the Service.
          </p>
          <p className="text-gray-700 mb-4 leading-relaxed">
            You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.
          </p>
          <p className="text-gray-700 mb-8 leading-relaxed">
            Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.
          </p>

          <h2 className="text-2xl font-bold text-gray-900 mb-4">Disclosure of Your Personal Data</h2>
          
          <h3 className="text-xl font-semibold text-gray-900 mb-3">Business Transactions</h3>
          <p className="text-gray-700 mb-6 leading-relaxed">
            If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy
          </p>

          <h3 className="text-xl font-semibold text-gray-900 mb-3">Law Enforcement</h3>
          <p className="text-gray-700 mb-6 leading-relaxed">
            Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
          </p>

          <h3 className="text-xl font-semibold text-gray-900 mb-3">Other legal requirements</h3>
          <p className="text-gray-700 mb-4 leading-relaxed">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
          
          <ul className="list-disc pl-6 mb-8 space-y-1 text-gray-700">
            <li>Comply with a legal obligation</li>
            <li>Protect and defend the rights or property of the Company</li>
            <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
            <li>Protect the personal safety of Users of the Service or the public</li>
            <li>Protect against legal liability</li>
          </ul>

          <h2 className="text-2xl font-bold text-gray-900 mb-4">Security of Your Personal Data</h2>
          <p className="text-gray-700 mb-8 leading-relaxed">
            The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
          </p>

          <h2 className="text-2xl font-bold text-gray-900 mb-4">Detailed Information on the Processing of Your Personal Data</h2>
          <p className="text-gray-700 mb-8 leading-relaxed">
            The Service Providers We use may have access to Your Personal Data. These third-party vendors collect, store, use, process and transfer information about Your activity on Our Service in accordance with their Privacy Policies.
          </p>

          <h3 className="text-xl font-semibold text-gray-900 mb-3">Security of Your Personal Data</h3>
          <p className="text-gray-700 mb-6 leading-relaxed">
            We may use third-party Service providers to monitor and analyze the use of our Service.
          </p>

          <div className="space-y-6 mb-8">
            <div className="bg-blue-50 p-6 rounded-lg">
              <h4 className="text-lg font-semibold text-gray-900 mb-3">Google Analytics</h4>
              <p className="text-gray-700 mb-4 leading-relaxed">
                Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. Google may use the collected data to contextualize and personalize the ads of its own advertising network.
              </p>
              <p className="text-gray-700 mb-4 leading-relaxed">
                You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js and dc.js) from sharing information with Google Analytics about visits activity.
              </p>
              <p className="text-gray-700 leading-relaxed">
                For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: <a href="https://policies.google.com/privacy" className="text-blue-600 hover:text-blue-800 underline">https://policies.google.com/privacy</a>
              </p>
            </div>

            <div className="bg-purple-50 p-6 rounded-lg">
              <h4 className="text-lg font-semibold text-gray-900 mb-3">Matomo</h4>
              <p className="text-gray-700 leading-relaxed">
                Matomo is a web analytics service. You can visit their Privacy Policy page here: <a href="https://matomo.org/privacy-policy" className="text-blue-600 hover:text-blue-800 underline">https://matomo.org/privacy-policy</a>
              </p>
            </div>
          </div>

          <h3 className="text-xl font-semibold text-gray-900 mb-3">Email Marketing</h3>
          <p className="text-gray-700 mb-8 leading-relaxed">
            We may use Your Personal Data to contact You with newsletters, marketing or promotional materials and other information that may be of interest to You. You may opt-out of receiving any, or all, of these communications from Us by following the unsubscribe link or instructions provided in any email We send or by contacting Us.
          </p>

          <h3 className="text-xl font-semibold text-gray-900 mb-3">Payments</h3>
          <p className="text-gray-700 mb-4 leading-relaxed">
            We may provide paid products and/or services within the Service. In that case, we may use third-party services for payment processing (e.g. payment processors).
          </p>
          <p className="text-gray-700 mb-6 leading-relaxed">
            We will not store or collect Your payment card details. That information is provided directly to Our third-party payment processors whose use of Your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.
          </p>

          <div className="space-y-4 mb-8">
            <div className="bg-yellow-50 p-4 rounded-lg">
              <h4 className="font-semibold text-gray-900 mb-2">PayPal</h4>
              <p className="text-gray-700 text-sm">
                Their Privacy Policy can be viewed at <a href="https://www.paypal.com/webapps/mpp/ua/privacy-full" className="text-blue-600 hover:text-blue-800 underline">https://www.paypal.com/webapps/mpp/ua/privacy-full</a>
              </p>
            </div>

            <div className="bg-green-50 p-4 rounded-lg">
              <h4 className="font-semibold text-gray-900 mb-2">Authorize.net</h4>
              <p className="text-gray-700 text-sm">
                Their Privacy Policy can be viewed at <a href="https://www.authorize.net/company/privacy/" className="text-blue-600 hover:text-blue-800 underline">https://www.authorize.net/company/privacy/</a>
              </p>
            </div>
          </div>

          <h3 className="text-xl font-semibold text-gray-900 mb-3">Behavioral Remarketing</h3>
          <p className="text-gray-700 mb-4 leading-relaxed">
            The Company uses remarketing services to advertise to You after You accessed or visited our Service. We and Our third-party vendors use cookies and non-cookie technologies to help Us recognize Your Device and understand how You use our Service so that We can improve our Service to reflect Your interests and serve You advertisements that are likely to be of more interest to You.
          </p>
          <p className="text-gray-700 mb-4 leading-relaxed">
            These third-party vendors collect, store, use, process and transfer information about Your activity on Our Service in accordance with their Privacy Policies and to enable Us to:
          </p>

          <ul className="list-disc pl-6 mb-6 space-y-1 text-gray-700">
            <li>Measure and analyze traffic and browsing activity on Our Service</li>
            <li>Show advertisements for our products and/or services to You on third-party websites or apps</li>
            <li>Measure and analyze the performance of Our advertising campaigns</li>
          </ul>

          <p className="text-gray-700 mb-4 leading-relaxed">
            Some of these third-party vendors may use non-cookie technologies that may not be impacted by browser settings that block cookies. Your browser may not permit You to block such technologies. You can use the following third-party tools to decline the collection and use of information for the purpose of serving You interest-based advertising:
          </p>

          <ul className="list-disc pl-6 mb-6 space-y-1 text-gray-700">
            <li>The NAI's opt-out platform: <a href="http://www.networkadvertising.org/choices/" className="text-blue-600 hover:text-blue-800 underline">http://www.networkadvertising.org/choices/</a></li>
            <li>The EDAA's opt-out platform <a href="http://www.youronlinechoices.com/" className="text-blue-600 hover:text-blue-800 underline">http://www.youronlinechoices.com/</a></li>
            <li>The DAA's opt-out platform: <a href="http://optout.aboutads.info/?c=2&lang=EN" className="text-blue-600 hover:text-blue-800 underline">http://optout.aboutads.info/?c=2&lang=EN</a></li>
          </ul>

          <p className="text-gray-700 mb-4 leading-relaxed">
            You may opt-out of all personalized advertising by enabling privacy features on Your mobile device such as Limit Ad Tracking (iOS) and Opt Out of Ads Personalization (Android). See Your mobile device Help system for more information.
          </p>

          <p className="text-gray-700 mb-4 leading-relaxed">
            To read more about the technologies used by these third-party vendors and their cross-device capabilities please refer to the Privacy Policy of each vendor listed below.
          </p>

          <p className="text-gray-700 mb-4 leading-relaxed">The third-party vendors We use are:</p>

          <div className="space-y-6 mb-8">
            <div className="bg-red-50 p-6 rounded-lg">
              <h4 className="text-lg font-semibold text-gray-900 mb-3">Google Ads (AdWords)</h4>
              <p className="text-gray-700 mb-4 leading-relaxed">
                Google Ads (AdWords) remarketing service is provided by Google Inc.
              </p>
              <p className="text-gray-700 mb-4 leading-relaxed">
                You can opt-out of Google Analytics for Display Advertising and customize the Google Display Network ads by visiting the Google Ads Settings page: <a href="http://www.google.com/settings/ads" className="text-blue-600 hover:text-blue-800 underline">http://www.google.com/settings/ads</a>
              </p>
              <p className="text-gray-700 mb-4 leading-relaxed">
                Google also recommends installing the Google Analytics Opt-out Browser Add-on - <a href="https://tools.google.com/dlpage/gaoptout" className="text-blue-600 hover:text-blue-800 underline">https://tools.google.com/dlpage/gaoptout</a> - for your web browser. Google Analytics Opt-out Browser Add-on provides visitors with the ability to prevent their data from being collected and used by Google Analytics.
              </p>
              <p className="text-gray-700 leading-relaxed">
                For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: <a href="https://policies.google.com/privacy" className="text-blue-600 hover:text-blue-800 underline">https://policies.google.com/privacy</a>
              </p>
            </div>

            <div className="bg-indigo-50 p-6 rounded-lg">
              <h4 className="text-lg font-semibold text-gray-900 mb-3">Facebook</h4>
              <p className="text-gray-700 mb-4 leading-relaxed">
                Facebook remarketing service is provided by Facebook Inc.
              </p>
              <p className="text-gray-700 mb-4 leading-relaxed">
                You can learn more about interest-based advertising from Facebook by visiting this page: <a href="https://www.facebook.com/help/516147308587266" className="text-blue-600 hover:text-blue-800 underline">https://www.facebook.com/help/516147308587266</a>
              </p>
              <p className="text-gray-700 mb-4 leading-relaxed">
                To opt-out from Facebook's interest-based ads, follow these instructions from Facebook: <a href="https://www.facebook.com/help/568137493302217" className="text-blue-600 hover:text-blue-800 underline">https://www.facebook.com/help/568137493302217</a>
              </p>
              <p className="text-gray-700 mb-4 leading-relaxed">
                Facebook adheres to the Self-Regulatory Principles for Online Behavioural Advertising established by the Digital Advertising Alliance. You can also opt-out from Facebook and other participating companies through the Digital Advertising Alliance in the USA <a href="http://www.aboutads.info/choices/" className="text-blue-600 hover:text-blue-800 underline">http://www.aboutads.info/choices/</a>, the Digital Advertising Alliance of Canada in Canada <a href="http://youradchoices.ca/" className="text-blue-600 hover:text-blue-800 underline">http://youradchoices.ca/</a> or the European Interactive Digital Advertising Alliance in Europe <a href="http://www.youronlinechoices.eu/" className="text-blue-600 hover:text-blue-800 underline">http://www.youronlinechoices.eu/</a>, or opt-out using your mobile device settings.
              </p>
              <p className="text-gray-700 leading-relaxed">
                For more information on the privacy practices of Facebook, please visit Facebook's Data Policy: <a href="https://www.facebook.com/privacy/explanation" className="text-blue-600 hover:text-blue-800 underline">https://www.facebook.com/privacy/explanation</a>
              </p>
            </div>
          </div>

          <h2 className="text-2xl font-bold text-gray-900 mb-4">Children's Policy</h2>
          <p className="text-gray-700 mb-4 leading-relaxed">
            Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
          </p>
          <p className="text-gray-700 mb-8 leading-relaxed">
            If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.
          </p>

          <h2 className="text-2xl font-bold text-gray-900 mb-4">Links to Other Websites</h2>
          <p className="text-gray-700 mb-4 leading-relaxed">
            Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
          </p>
          <p className="text-gray-700 mb-8 leading-relaxed">
            We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
          </p>

          <h2 className="text-2xl font-bold text-gray-900 mb-4">Changes to this Privacy Policy</h2>
          <p className="text-gray-700 mb-4 leading-relaxed">
            We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
          </p>
          <p className="text-gray-700 mb-4 leading-relaxed">
            We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
          </p>
          <p className="text-gray-700 mb-8 leading-relaxed">
            You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
          </p>

          <h2 className="text-2xl font-bold text-gray-900 mb-4">Contact Us</h2>
          <p className="text-gray-700 mb-8 leading-relaxed">
            If you have any questions about this Privacy Policy, You can contact us By email: info@botandtable.com
          </p>

        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicyPage; 